### PR TITLE
The image is resized by Evernote to create the note enml.

### PR DESCRIPTION
**Pull request by zhougy0717**
Use the enml attributes instead of the attributes retrieved from Evernote note resource API.

### CODE REVIEW

**Comment by zhougy0717** [comment]
Have you ever tested your latest enml2html? It seems you have re-written it. But it seems not work for me at all. Could you look at these lines?
```
  return $('body').html()
    .replace(/\s*\n+\s*/g, '')
    .trim()
```
the enml string doesn't have the standard html overload. Example:
```
<html>
 <head></head>
 <body>
</body>
</html>
```
So `$('body').html()` always comes to `null`. That will absolutely break the code.

**Comment by nswbmw** [comment]
1. 你先 rebase 到最新试试
2. 你给的例子应该没有问题
3. 大半年前重写后没有再使用过，可能 enml 格式变了，返回 null 应该是没有 body 标签，这个你打印一下很容易查到哪有问题，可以打印 $.html() 看下

```js
const cheerio = require('cheerio')
const html = `
<html>
<head></head>
<body>
</body>
</html>`
const $ = cheerio.load(html)
console.log(typeof $('body').html()) // string
```

**Comment by zhougy0717** [comment]
我打印过了的，确实没有body标签
我查看你重写前转出来的html也没有body标签，但以前没有这一句，所以没问题。

**Comment by nswbmw** [comment]
我已经忘记为什么把  `$.html() -> $('body').html()` 了。已经修复回 `$.html()`，你可以 rebase 下

**Pull request merged**
